#!/bin/bash
#
#
# Options for Slurm sbatch begin with '#SBATCH'. Everything else is shell commands.
#
#SBATCH --job-name    fastqcduc        # Job name
#SBATCH --output      fastqcduc.out # File to store stdout, with jobid in the name
#SBATCH --error       fastqcduc.err # File to store stderr, with jobid in the name
#SBATCH --partition   defq	   # Partition name to run the job in
#SBATCH --nodes       1            # Total number of nodes
#SBATCH --ntasks      1            # Total number of tasks
#SBATCH --mem         15000         # 2000 MB of Memory
#SBATCH --time        23:59:00   # Maximum run time (d-hh:mm:ss) -- 3 minutes here
#SBATCH --mail-user   gregory.chorak@student.montana.edu # user to send emails to
#SBATCH --mail-type   ALL                    # Email on: BEGIN, END, FAIL & REQUEUE
## Run 'man sbatch' for more information on the options above.


cd /mnt/lustrefs/store/gregory.chorak/RefData

fastqc *_ARduked.fq
